version: 1.0.0

dev:
  Logging:
    stdout: true
    level: debug
  server:
    port: ":7004"
    rmqurl: "amqp://guest:guest@localhost:5000/"

sit:
  Logging:
    stdout: false
    level: debug
    path: applog.log
  server:
    port: ":7004"
    rmqurl: "amqp://guest:guest@localhost:5000/"

prod:
  Logging:
    stdout: false
    level: debug
    path: applog.log
  server:
    port: ":7004"
    rmqurl: "amqp://guest:guest@localhost:5000/"
