version: 1.0.0

dev:
  Logging:
    stdout: true
    level: debug
  server:
    port: ":7004"
  database:
    host: "localhost"
    port: 15432
    username: "admin"
    password: "GTM@fis2019."
    name: "cmpdata"
    schema: "public"
    logmode: true

sit:
  Logging:
    stdout: false
    level: debug
    path: applog.log
  server:
    port: ":7004"
  database:
    host: "localhost"
    port: 5432
    username: "admin"
    password: "Gtm@fis2019."
    name: "cmpdata"
    schema: "public"
    logmode: true

prod:
  Logging:
    stdout: false
    level: debug
    path: applog.log
  server:
    port: ":7004"
  database:
    host: "localhost"
    port: 5432
    username: "admin"
    password: "Gtm@fis2019."
    name: "cmpdata"
    schema: "public"
    logmode: true
